env:
  global:
  - secure: afqIu7SQ/GoytD1WjbYDBok8+8YPEYIwOGWM2jtx5JW5qVD+qRZIWL5CY0MWZix28MVGjafbta3TRhM7SWPVpm+O9fnaKmW5BP3ywex/Imu9t4MSXbMY0FTXk5HArMSHXB78pfTjqVpsUey8m8gC64kecN+c+cpcNCT+MRkHL7Q=
  - secure: WXXh59l5xUhIaMLbgCLE7b0AqCqN9Ms11r2YkU2SYg5z0pXeJVdbs7DX7oaE+OwOXyZOWnzugVbQv5USZ1v/FwDBNnr16jxXXGDT2+TL1myfS9YT+kj7zDf/OWtMzmebf5dj6OSi7/1qDQgCyElQZJIRpN8pENsC1qmDHPbEyMo=
